# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BreadMan' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


	pod 'SDWebImage', '~> 4.0'
	pod 'SVProgressHUD'
	pod 'IQKeyboardManagerSwift'
	pod 'Alamofire', '~> 4.0.1'
	pod 'SkyFloatingLabelTextField'
	pod 'SWRevealViewController'

end
